import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import SecHeadArrowL from '../static/pinkArrow.png'
import SecHeadArrowR from '../static/blue-Arrow.png'
import BitScaleLogo from '../static/bitscale-logo.png'
import ChainLinkLogo from '../static/chainlink-logo.png'
import ImmuteableLogo from '../static/immuteable-logo.png'
import LotusLogo from '../static/lotus_white.png'
import BitcoinLogo from '../static/Bitcoincom.png'
import QuantstampLogo from '../static/quantstamp-logo.png'
import RoadmapBg from '../static/roadmap-bg.png'
import RoadmapBlueLine from '../static/roadmap-blue-line.png'
import RoadmapPinkLine from '../static/roadmap-pink-line.png'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Omini Verse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar/>
        <div className={styles.secHeadingCon}>
          <div className={styles.secHeadingWrap}>
            <div className={styles.secHeadImgL}>
              <Image src={SecHeadArrowL} layout="responsive" alt="arrow"></Image>
            </div>
            <h3>Omniverse</h3>
            <div className={styles.secHeadImgR}>
              <Image src={SecHeadArrowR} layout="responsive" alt="arrow"></Image>
            </div>
          </div>
          <h1>RoadMap</h1>
        </div>
        <div className={styles.roadmapCon}>
          {/* First Phase */}
          <div className={styles.roadmapWrap}>
            <div className={styles.ContL}>
              <h1 className={styles.purpletxt}>Mar 2022</h1>
              <div className={styles.BgWrap}>
                <div className={styles.BgImg}>
                  <Image src={RoadmapBg} layout="responsive" alt="bg"></Image>
                </div>
                <div className={styles.roadmapTxt}>
                  <h3>Community &amp; Core team Growth</h3>
                  <p>Launched Socials and github launched to 
                  establish, foster and grow community.</p>
                </div>
              </div>
            </div>
            <div className={styles.ContR}>
              <div className={styles.roadlineImg}>
                <Image src={RoadmapBlueLine} layout="responsive" alt="blueline"></Image>
              </div>
            </div>
          </div>
          {/* Second Phase */}
          <div className={styles.roadmapWrap}>
            <div className={styles.ContR}>
              <div className={styles.roadlineBlue}>
                <div className={styles.alignLine}>
                  <Image src={RoadmapPinkLine} layout="responsive" alt="blueline"></Image>
                </div>
              </div>
            </div>
            <div className={styles.ContL}>
              <h1>APR 2022</h1>
              <div className={styles.BgWrap}>
                <div className={styles.BgImg}>
                  <Image src={RoadmapBg} layout="responsive" alt="bg"></Image>
                </div>
                <div className={styles.roadmapTxt}>
                  <h3>Capital Raise</h3>
                  <p>Expanded team and added core contributors to collaborate on development.</p>
                </div>
              </div>
            </div>
          </div>
          {/* Third Phase */}
          <div className={styles.roadmapWrap}>
            <div className={styles.ContL}>
              <h1>Mar 2022</h1>
              <div className={styles.BgWrap}>
                <div className={styles.BgImg}>
                  <Image src={RoadmapBg} layout="responsive" alt="bg"></Image>
                </div>
                <div className={styles.roadmapTxt}>
                  <h3>GREG</h3>
                  <p>Launch Website showcasing interchain nft asset transfer.
                  Genesis omniverse greg omni-nft colection. </p>
                </div>
              </div>
            </div>
            <div className={styles.ContR}>
              <div className={styles.roadlineImg}>
                <Image src={RoadmapBlueLine} layout="responsive" alt="blueline"></Image>
              </div>
            </div>
          </div>
          {/* Forth Phase */}
          <div className={styles.roadmapWrap}>
            <div className={styles.ContR}>
              <div className={styles.roadlineBlue}>
                <div className={styles.alignLine}>
                  <Image src={RoadmapPinkLine} layout="responsive" alt="blueline"></Image>
                </div>
              </div>
            </div>
            <div className={styles.ContL}>
              <h1>June 2022</h1>
              <div className={styles.BgWrap}>
                <div className={styles.BgImg}>
                  <Image src={RoadmapBg} layout="responsive" alt="bg"></Image>
                </div>
                <div className={styles.roadmapTxt}>
                  <h3>Omni X</h3>
                  <p>Alpha NFT marketplace infrastructure release.</p>
                </div>
              </div>
            </div>
          </div>
          {/* Fifth Phase */}
          <div className={styles.roadmapWrap}>
            <div className={styles.ContL}>
              <h1>Q3 2022</h1>
              <div className={styles.BgWrap}>
                <div className={styles.BgImg}>
                  <Image src={RoadmapBg} layout="responsive" alt="bg"></Image>
                </div>
                <div className={styles.roadmapTxt}>
                  <h3>faction nfts</h3>
                  <p>NFT PFP Collections: faction specific GENESIS collections.
                  Engagement Competitions: rewards for world building, fan art, and lore production. </p>
                </div>
              </div>
            </div>
            <div className={styles.ContR}>
              <div className={styles.roadlineImg}>
                <Image src={RoadmapBlueLine} layout="responsive" alt="blueline"></Image>
              </div>
            </div>
          </div>
          {/* Sixth Phase */}
          <div className={styles.roadmapWrap}>
            <div className={styles.ContR}>
              <div className={`${styles.roadlineBlue} ${styles.linehide}`}>
                <div className={styles.alignLine}>
                  <Image src={RoadmapPinkLine} layout="responsive" alt="blueline"></Image>
                </div>
              </div>
            </div>
            <div className={styles.ContL}>
              <h1>Q4 2022</h1>
              <div className={styles.BgWrap}>
                <div className={styles.BgImg}>
                  <Image src={RoadmapBg} layout="responsive" alt="bg"></Image>
                </div>
                <div className={styles.roadmapTxt}>
                  <h3>Omni Wars</h3>
                  <p>Alpha gameplay launch</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* Partners Section */}
        <div className={styles.secHeadingCon}>
          <div className={styles.secHeadingWrap}>
            <div className={styles.secHeadImgL}>
              <Image src={SecHeadArrowL} layout="responsive" alt="arrow"></Image>
            </div>
            <h3>Omniverse</h3>
            <div className={styles.secHeadImgR}>
              <Image src={SecHeadArrowR} layout="responsive" alt="arrow"></Image>
            </div>
          </div>
          <h1>Our Partners</h1>
        </div>
        <div className={styles.partCompGrid}>
          <div className={styles.PartCompWrap}>
            <Image src={BitScaleLogo} alt="bitscale" width={200}></Image>
          </div>
          <div className={styles.PartCompWrap}>
            <Image src={ChainLinkLogo} alt="bitscale" width={240}></Image>
          </div>
          <div className={styles.PartCompWrap}>
            <Image src={ImmuteableLogo} alt="bitscale" width={350}></Image>
          </div>
          <div className={styles.PartCompWrap}>
            <Image src={LotusLogo} alt="bitscale" width={180}></Image>
          </div>
          <div className={styles.PartCompWrap}>
            <Image src={BitcoinLogo} alt="bitscale" width={280}></Image>
          </div>
          <div className={styles.PartCompWrap}>
            <Image src={QuantstampLogo} alt="bitscale" width={370}></Image>
          </div>
        </div>
      </div>
      <Footer/>
    </>
  )
}

export default Home
