import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import NFT from '../components/NFT'
// import MintMainImg from '../static/mint-main.png'
import MintImgBottom from '../static/mintImg-bg.png'
import PloyGoneImg from '../static/polygon logo.png'
import MinusSign from '../static/minus-sign.png'
import PlusSign from '../static/plus-sign.png'
import HeadingImg from '../static/head-img.png'
import mintstyles from '../styles/mint.module.css'

const mint: NextPage = () => {
  return (
    <>
      <Head>
        <title>Omini Verse | Mint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={mintstyles.mintHero}> 
        <Navbar/>
        <div className={mintstyles.container}>
          <div className={mintstyles.mintImgWrap}>
            <div className={mintstyles.mintImgT}>
              {/* <Image src={MintMainImg} alt="mint" layout='responsive' /> */}
              <video
                style={{ objectFit: "cover" }}
                width="100%"
                height="100%"
                autoPlay
                loop
                muted
              >
                <source src='../static/vid.mp4' type="video/mp4" />
                Your browser does not support the video tag.
              </video>
            </div>
            <div className={mintstyles.mintImgB}>
              <Image src={MintImgBottom} alt="mint background" layout='responsive' />
              <div className={mintstyles.mintImgtext}>
                <h1>&#40;GREG, GREG&#41;</h1>
              </div>
            </div>
          </div>
          <div className={mintstyles.mintDesc}>
            <h1>Description</h1>
            <div className={mintstyles.mintDescSec}>
              <p>Welcome to the omniverse</p>
              <p>greg is our genesis collection that represents our community and technological breakthroughs</p>
              <p>mint greg below from any chain you wish and transfer him to any other chain using the “Transfer” box below</p>
              <p>5 mints per wallet</p>
            </div>
            <div className={mintstyles.mintDataGrid}>
              <div className={mintstyles.mintDataWrap}>
                <h5>MINTED</h5>
                <span>0/750</span>
              </div>
              <span className={mintstyles.line}></span>
              <div className={mintstyles.mintDataWrap}>
                <h5>PRICE</h5>
                <span>250 <Image src={PloyGoneImg} width={29.84} height={25.46} alt="ikon"></Image></span>
              </div>
              <span className={mintstyles.line}></span>
              <div className={mintstyles.mintDataWrap}>
                <h5>QUANTITY</h5>
                <div className={mintstyles.counterWrap}>
                  <button><Image src={MinusSign} alt="minus"></Image></button>
                  <span>1</span>
                  <button><Image src={PlusSign} alt="plus"></Image></button>
                </div>
              </div>
            </div>
            <div className={mintstyles.mintBtnWrap}>
              <button type='button'>MINT NOW</button>
            </div>
          </div>
        </div>
      </div>
      <div className={mintstyles.mintSecBg}>
        <div className={mintstyles.mintheadingImg}>
            <div className={mintstyles.headImg}>
              <Image src={HeadingImg} alt='mint head' layout='responsive'></Image>
            </div>
            <h1>YOUR NFTS</h1>
          </div>
        <NFT/>
        <Footer/>
      </div>
    </>
  )
}

export default mint
